name: Toga Calculator CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libcairo2-dev \
          libgirepository1.0-dev \
          python3-gi \
          gir1.2-gtk-3.0 \
          pkg-config \
          libgtk-3-dev \
          libgdk-pixbuf2.0-dev \
          libpango1.0-dev \
          libglib2.0-dev \
          build-essential \
          cmake \
          ninja-build \
          git \
          meson

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install toga

    - name: Run calculator app
      run: |
        python calculator_app.py