[tool.briefcase]
project_name = "Calculator"
bundle = "org.example"
version = "0.0.1"
url = "https://example.org/calculator"
license = "BSD license"
author = "Your Name"
author_email = "your.name@example.com"

[tool.briefcase.app.calculator]
formal_name = "Calculator"
description = "A simple calculator application"
icon = "resources/calculator"
sources = ["calculator.py"]
requires = [
    "toga>=0.3.0",
]


[tool.briefcase.app.calculator.macOS]
requires = [
    "toga-cocoa>=0.3.0",
    "std-nslog~=1.0.0",
]

[tool.briefcase.app.calculator.linux]
requires = [
    "toga-gtk>=0.3.0",
]

[tool.briefcase.app.calculator.linux.system.debian]
system_requires = [
    "libgirepository1.0-dev",
    "libcairo2-dev",
    "libpango1.0-dev",
    "libwebkitgtk-3.0-0",
    "gir1.2-webkit-3.0",
]

[tool.briefcase.app.calculator.linux.system.ubuntu]
system_requires = [
    "libgirepository1.0-dev",
    "libcairo2-dev",
    "libpango1.0-dev",
    "libwebkitgtk-3.0-0",
    "gir1.2-webkit-3.0",
]

[tool.briefcase.app.calculator.linux.system.fedora]
system_requires = [
    "gobject-introspection-devel",
    "cairo-gobject-devel",
    "webkit2gtk3",
]

[tool.briefcase.app.calculator.windows]
requires = [
    "toga-winforms>=0.3.0",
]

[tool.briefcase.app.calculator.android]
requires = [
    "toga-android>=0.3.0",
]

[tool.briefcase.app.calculator.iOS]
requires = [
    "toga-iOS>=0.3.0",
]

[tool.briefcase.app.calculator.web]
requires = [
    "toga-web>=0.3.0",
]
style_framework = "Shoelace v2.0"