name: Toga Calculator CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libcairo2-dev \
          libgirepository1.0-dev \
          python3-gi \
          gir1.2-gtk-3.0 \
          pkg-config \
          libgtk-3-dev \
          libgdk-pixbuf2.0-dev \
          libpango1.0-dev \
          libglib2.0-dev \
          build-essential \
          cmake \
          ninja-build \
          git \
          meson \
          gobject-introspection \
          python3-dev \
          python3-gi-cairo \
          gir1.2-glib-2.0 \
          gir1.2-cairo-1.0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Update pip and setuptools
      run: |
        python -m pip install --upgrade pip setuptools wheel

    - name: Install Python dependencies
      run: |
        pip install --no-build-isolation pycairo
        pip install --no-build-isolation pygobject
        pip install toga briefcase

    - name: Run calculator app
      run: python calculator_app.py