name: Python Kivy Application

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libsdl2-dev \
          libsdl2-image-dev \
          libsdl2-mixer-dev \
          libsdl2-ttf-dev \
          libportmidi-dev \
          libswscale-dev \
          libavformat-dev \
          libavcodec-dev \
          zlib1g-dev \
          libgstreamer1.0-dev \
          libmtdev-dev \
          xvfb
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install kivy pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Run tests with virtual display
      run: |
        xvfb-run -a python -m pytest tests/ -v
      if: hashFiles('tests/**/*.py') != ''
      
    - name: Run Kivy app with virtual display
      run: |
        export KIVY_NO_ARGS=1
        export KIVY_NO_CONSOLELOG=1
        xvfb-run -a python calculator_app.py --headless
      
    - name: Build distribution
      run: |
        pip install build
        python -m build
      if: hashFiles('setup.py') != '' || hashFiles('pyproject.toml') != ''
