name: Python application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Checkout the code from GitHub repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up Python environment
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Set environment variable to run Kivy in headless mode
    - name: Set Kivy to run in headless mode
      run: |
        echo "KIVY_METRICS_DENSITY=2" >> $GITHUB_ENV
        echo "KIVY_METRICS_FALLBACK=1" >> $GITHUB_ENV
        echo "KIVY_METRICS_DENSITY=1" >> $GITHUB_ENV
        export DISPLAY=:0

    # Run the Kivy app (example command to test if it's working)
    - name: Test Kivy app
      run: |
        python calculator_app.py
