name: Toga Calculator CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          python3-dev \
          python3-gi \
          python3-gi-cairo \
          python3-cairo \
          python3-setuptools \
          libcairo2-dev \
          libgirepository1.0-dev \
          gir1.2-gtk-3.0 \
          pkg-config \
          libgtk-3-dev \
          libgdk-pixbuf2.0-dev \
          libpango1.0-dev \
          libglib2.0-dev \
          gir1.2-glib-2.0 \
          gir1.2-cairo-1.0 \
          gobject-introspection \
          build-essential \
          cmake \
          ninja-build \
          git \
          meson

    - name: Verify pkg-config paths for GObject Introspection
      run: |
        pkg-config --exists --print-errors "gobject-introspection-1.0"
        pkg-config --exists --print-errors "girepository-1.0"
        echo "PKG_CONFIG_PATH before: $PKG_CONFIG_PATH"
        export PKG_CONFIG_PATH="$PKG_CONFIG_PATH:/usr/lib/pkgconfig:/usr/share/pkgconfig"
        echo "PKG_CONFIG_PATH after: $PKG_CONFIG_PATH"
        pkg-config --modversion gobject-introspection-1.0 || echo "gobject-introspection-1.0 not found"
        pkg-config --modversion girepository-1.0 || echo "girepository-1.0 not found"
        pkg-config --modversion girepository-2.0 || echo "girepository-2.0 not found"
        ls -la /usr/lib/pkgconfig/ | grep girepo

    - name: Install PyGObject using system package
      run: |
        sudo apt-get install -y python3-gi

    - name: Update pip and install build tools
      run: |
        python -m pip install --upgrade pip setuptools wheel

    - name: Install Toga with specific dependencies
      run: |
        pip install pycairo
        CFLAGS="-I/usr/include/gobject-introspection-1.0" PKG_CONFIG_PATH="/usr/lib/pkgconfig:/usr/share/pkgconfig" pip install toga briefcase

    - name: Run calculator app
      run: python calculator_app.py